version: '3.8'

services:
  app:
    build: .
    container_name: real-time-chat-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatdb
      - JWT_SECRET=your_jwt_secret
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASS=your_email_password
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
